FROM almalinux:9

RUN dnf install -y \
      gcc gcc-c++ make \
      cmake \
      git \
      python3 python3-pip \
      docker \
    && dnf clean all

# install Conan
RUN pip3 install --no-cache-dir conan
