---
services:
  gitlab:
    image: gitlab/gitlab-ce:17.11.2-ce.0
    hostname: ${GITLAB_HOST}
    container_name: gitlab
    restart: unless-stopped
    ports:
      # nginx['listen_port'] = 80 should have worked according to
      # https://docs.gitlab.com/omnibus/settings/nginx/#set-the-nginx-listen-port
      # but it seems to be ignored, so we need to set the port here.
      - "${GITLAB_PORT}:${GITLAB_PORT}"
    environment:
      GITLAB_ROOT_EMAIL: "admin@${GITLAB_HOST}"
      GITLAB_ROOT_PASSWORD: "Abcd1234!"
      # Set external_url to the correct port so all links will be correct (for example link to runner) &
      # disable cluster mode to avoid more memory usage
      # (https://docs.gitlab.com/administration/operations/puma/#disable-puma-clustered-mode-in-memory-constrained-environments) &
      # let puma listen on non-default port (which happens to be the same as our external_url port):
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://${GITLAB_HOST}:${GITLAB_PORT}'
        puma['worker_processes'] = 0
        puma['port'] = 8081
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:v17.11.1
    container_name: gitlab-runner
    depends_on:
      - gitlab
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab_runner_config:/etc/gitlab-runner
    # The extra_hosts make sure that we can access GitLab from the runner and the host using the same hostname.
    extra_hosts:
      - "gitlab.local:host-gateway"
    entrypoint: >
      gitlab-runner run --user=gitlab-runner --working-directory=/home/gitlab-runner

  nexus:
    image: sonatype/nexus3:3.79.1-java17-alpine
    container_name: nexus
    restart: unless-stopped
    ports:
      - "${NEXUS_PORT}:8081"
    volumes:
      - nexus_data:/nexus-data

  registry:
    image: registry:3
    container_name: registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
    restart: unless-stopped
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"

  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    ports:
      - "${DOCKER_REGISTRY_UI_PORT}:80"
    restart: unless-stopped
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000

volumes:
  gitlab_config:
  gitlab_logs:
  gitlab_data:
  gitlab_runner_config:
  nexus_data:
  registry_data:
