image: conan-cpp:latest

stages:
  - build
  - test
  - build_and_upload_image
  - deploy_tst

build:
  stage: build
  script:
    - conan build . --build=missing
  artifacts:
    paths:
      - build/Release/unit_tests
      - build/Release/fibonacci-webservice

test:
  stage: test
  script:
    - build/Release/unit_tests --gtest_output=xml:build/test-results.xml
  artifacts:
    reports:
      junit: build/test-results.xml

build_and_upload_image:
  stage: build_and_upload_image
  script:
    - ./build-image.sh
  only:
    - main

deploy_tst:
  stage: deploy_tst
  environment: tst
  image: ansible:latest
  script:
    - ./deploy-to.sh tst
  only:
    - main
