image: conan-cpp:latest

stages:
  - build_and_upload
  - deploy_tst

build_and_upload:
  stage: build_and_upload
  script:
    - ./build-image.sh
  only:
    - main

deploy_tst:
  stage: deploy_tst
  environment: tst
  image: ansible:latest
  script:
    - ./deploy-to.sh tst
  only:
    - main
