image: conan-cpp:latest

# We need to get the full history so we can automatically generate a version:
variables:
  GIT_DEPTH: "0"

stages:
  - build_and_upload
  - deploy_tst

build_and_upload:
  stage: build_and_upload
  script:
    - git show-ref --tags
    - git log -1 --oneline
    - git tag --merged HEAD
    - git log --graph --oneline --decorate --all
    - git tag --sort=-creatordate --list 'webui-*' | head -n1
    - git rev-list --ancestry-path HEAD...ce1b1110f035135b9369c0e01ef5a28e75db14fa
    - git merge-base HEAD ce1b1110f035135b9369c0e01ef5a28e75db14fa
    - git describe --tags --abbrev=0 --match 'webui-*'
    - ./build-image.sh
  only:
    - main

deploy_tst:
  stage: deploy_tst
  environment: tst
  image: ansible:latest
  script:
    - ./deploy-to.sh tst
  only:
    - main
